name = "supermemory"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "6df98c892b3744ccb0c631d9f60d6697" },
	{ binding = "RECOMMENDATIONS", id = "83bc7055226c4657948141c2ff9a5425" }
]

env.production.kv_namespaces = [
	{ binding = "CANVAS_SNAPS", id = "2b6cff2fa30c489788f83e9ae7896c38" },
	{ binding = "RECOMMENDATIONS", id = "e8f63c891dc64718ac4f5d41de9aca86" }
]

[ai]
binding = "AI"

[placement]
mode = "smart"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "supermemory-r2"

[[d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "eecd4f5c-a9a7-4a1a-a158-c2ffed6f143b"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-prod"
database_id = "2a0f081f-39b7-489e-96e6-5cc989643738"

[env.preview.ai]
binding = "AI"

[[env.preview.d1_databases]]
binding = "DATABASE"
database_name = "supermemory-db-preview"
database_id = "eecd4f5c-a9a7-4a1a-a158-c2ffed6f143b"

[env.production.ai]
binding = "AI"