name = "new-cf-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-02-23"
node_compat = true

tail_consumers = [{service = "new-cf-ai-backend-tail"}]

[[services]]
binding = "THREAD"
service = "tweet-thread"
entrypoint = "ThreadWorker"

# [env.preview]
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "supermem-vector-dev"

# [[vectorize]]
# binding = "VECTORIZE_INDEX"
# index_name = "supermemory"

[ai]
binding = "AI"

# [[queues.producers]]
#  queue = "batch-vector-queue"
#  binding = "MY_QUEUE"

#  [[queues.consumers]]
#  queue = "batch-vector-queue"

[[kv_namespaces]]
binding = "KV"
id = "f49c445a98b74884b3dc689fe9d16def"
preview_id = "8931517d9e70486f92629dc7eb248946"

[placement]
mode = "smart"

[[queues.producers]]
  queue = "prod-embedchunks-queue"
  binding ="EMBEDCHUNKS_QUEUE"

[[queues.consumers]]
  queue = "prod-embedchunks-queue"
  max_batch_size = 100
  max_retries = 3
  dead_letter_queue = "prod-embedchunks-dlq"


[[d1_databases]]
binding = "DATABASE"
database_name = "prod-d1-supermemory"
database_id = "f527a727-c472-41d4-8eaf-3d7ba0f2f395"